name: Test, Build and Deploy Staging
on:
  push:
    branches:
      - 'main'
env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT_STAGING }}
  RUN_REGION: europe-west2
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache Node Modules
        id: test-npm
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-v12-${{ hashFiles('package-lock.json') }}
      - name: Install All Dependencies
        if: steps.test-npm.outputs.cache-hit != 'true'
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Run Linter
        run: npm run lint
  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT_STAGING }}
      - name: Build
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
